### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by zufukatana** [CodeXTF2/ScreenshotBOF#11]
coupled with https://github.com/Octoberfest7/MemFiles.git , it would be interesting to avoid dropping even bmp on disk, weird but Symantec didn't like it. I guess if the bmp is stored in beacons memory then fetch via MemFiles , then of course rendered from download tab.  I don't know if the initialized memory could hold a full screenshot.

**Comment by CodeXTF2** [comment]
Pass 1 as the arg after the filename and itll download fully in memory
without touching disk

**Comment by zufukatana** [comment]
Read the readme I guess !!!!!!! haha sorry works perfectly.

**Comment by CodeXTF2** [comment]
lol nice, have fun
