### ISSUE TITLE
error

### ISSUE THREAD

**Issue by b4sh1t1** [CodeXTF2/ScreenshotBOF#7]
Hi, 

im getting this error in 23 line.

@('2032867078', 'sad.bmp')
[02:16:30] Function call &beacon_inline_execute failed: The BOF content (arg 2) is empty. Did you read the right file? at screenshotBOF.cna:23

the project i build fine with no issue.

https://prnt.sc/6aOxLmLGZizX

any suggestion ?

**Comment by CodeXTF2** [comment]
Hi, I recently merged a PR, that might be the issue. Try the latest release zip. I'll fix the PR asap.

**Comment by CodeXTF2** [comment]
Hi, i just checked the current code from the PR, and while there are some changes I am making it doesnt seem broken. It was also functional when I tested it before merging it. Can you verify that the bin folder contains the following files?
![image](https://user-images.githubusercontent.com/29991665/199203685-44f6a32c-930a-44aa-b4a3-c87fc9fc5d99.png)

**Comment by CodeXTF2** [comment]
Current version is tested working, closing the issue. Reopen it if you still have the issue on the latest version
