### ISSUE TITLE
SaveHBITMAPToFile truncates filename when downloading direct to beacon

### ISSUE THREAD

**Issue by peterwsmdsec** [CodeXTF2/ScreenshotBOF#9]
The SaveHBITMAPToFile function truncates the output filename (lpszFileName):

Source.cpp (line 241)

`downloadFile((char*)lpszFileName, sizeof(lpszFileName), (char*)bmpdata, (int)(sizeof(BITMAPFILEHEADER) + dwDIBSize));`

sizeof() should be strlen().

**Comment by CodeXTF2** [comment]
oh ok thanks! Will fix it in a sec

**Comment by peterwsmdsec** [comment]
Thanks mate! I was about to DM you but thought this would be easier.

**Comment by CodeXTF2** [comment]
np. Was a surprise seeing u here lol

**Comment by peterwsmdsec** [comment]
![image](https://user-images.githubusercontent.com/64532298/204582980-11411ab1-5fd8-4c67-b9d6-f82efb067ec5.png)
I'm everywhere!
